import "./globals.css";

import { Inter } from "next/font/google";
import { ThemeProvider } from "@/providers/theme-provider";
import { TooltipProvider } from "@radix-ui/react-tooltip";

import type { Metadata } from "next";

import BaseLayout from "@/components/ui/base-layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Jody Yuantoro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning={true} lang="en">
      <body className={`${inter.className} flex justify-center p-8 md:p-24`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <TooltipProvider>
            <BaseLayout>{children}</BaseLayout>
          </TooltipProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
